# 次环境为多环境配置中的生产环境

server:
  port: 9101

spring:
  mail:
    host: smtp.qiye.163.com //邮箱服务器地址
    username: xxx@oo.com //用户名
    password: xxyyooo    //密码
    default-encoding: UTF-8
mail:
  fromMail:
    addr: xxx@oo.com  //以谁来发送邮件